In [3]:
import spacy
import pandas as pd

ModuleNotFoundError: No module named 'spacy'

In [ ]:
!pip install spacy

In [1]:
import spacy
import pandas as pd

ModuleNotFoundError: No module named 'spacy'

In [3]:
import sys
!{sys.executable} -m pip install spacy

Requirement already satisfied: spacy in c:\users\a\anaconda3\lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\a\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\a\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\a\anaconda3\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\a\anaconda3\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\a\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\a\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\a\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\a\anaconda3\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (0.25.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (4.66.4)
Requirement already satisfied: numpy>=1.19.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (2.32.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: jinja2 in c:\users\a\anaconda3\lib\site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in c:\users\a\anaconda3\lib\site-packages (from spacy) (69.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\a\anaconda3\lib\site-packages (from spacy) (23.2)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\a\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in c:\users\a\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\users\a\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\a\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\a\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\a\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\a\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.8.30)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\a\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\a\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\a\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\a\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\a\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\a\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\a\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\a\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in c:\users\a\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.27.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\a\anaconda3\lib\site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: anyio in c:\users\a\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.2.0)
Requirement already satisfied: httpcore==1.* in c:\users\a\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.2)
Requirement already satisfied: sniffio in c:\users\a\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\a\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\a\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\a\anaconda3\lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\a\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)

In [1]:
import spacy
import pandas as pd

In [3]:
npl = spacy.load("en_core_web_sm")

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

In [5]:
import sys
!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.1/12.8 MB 2.0 MB/s eta 0:00:07
     -- ------------------------------------- 0.7/12.8 MB 6.4 MB/s eta 0:00:02
     --- ------------------------------------ 1.2/12.8 MB 7.8 MB/s eta 0:00:02
     ----- ---------------------------------- 1.8/12.8 MB 8.7 MB/s eta 0:00:02
     ------- -------------------------------- 2.3/12.8 MB 9.3 MB/s eta 0:00:02
     --------- ------------------------------ 2.9/12.8 MB 9.7 MB/s eta 0:00:02
     ---------- ----------------------------- 3.5/12.8 MB 10.1 MB/s eta 0:00:01
     ------------ --------------------------- 4.1/12.8 MB 10.5 MB/s eta 0:00:01
     --------------- ------------------------ 4.8/12.8 MB 11.0 MB/s eta 0:00:01
     ----------------- ---------------------- 5.5/12.8 MB 11.3 MB/s eta 0:00:01
     ------------------ --------------------- 6.0/12.8 MB 11.3 MB/s eta 0:00:01
     -------------------- ------------------- 6.6/12.8 MB 11.3 MB/s eta 0:00:01
     ---------------------- ----------------- 7.4/12.8 MB 11.7 MB/s eta 0:00:01
     ------------------------- -------------- 8.1/12.8 MB 12.0 MB/s eta 0:00:01
     --------------------------- ------------ 8.7/12.8 MB 12.1 MB/s eta 0:00:01
     ----------------------------- ---------- 9.5/12.8 MB 12.4 MB/s eta 0:00:01
     ------------------------------ -------- 10.2/12.8 MB 12.5 MB/s eta 0:00:01
     --------------------------------- ----- 10.9/12.8 MB 13.6 MB/s eta 0:00:01
     ----------------------------------- --- 11.6/12.8 MB 13.6 MB/s eta 0:00:01
     ------------------------------------- - 12.2/12.8 MB 13.9 MB/s eta 0:00:01
     --------------------------------------  12.8/12.8 MB 13.9 MB/s eta 0:00:01
     --------------------------------------  12.8/12.8 MB 13.9 MB/s eta 0:00:01
     --------------------------------------  12.8/12.8 MB 13.9 MB/s eta 0:00:01
     --------------------------------------- 12.8/12.8 MB 12.1 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [5]:
nlp = spacy.load("en_core_web_sm")

NameError: name 'spacy' is not defined

In [10]:
import spacy
import pandas as pd

In [24]:
nlp = spacy.load("en_core_web_sm")

In [16]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twenty one years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
print(emma_ja)

emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twenty one years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own

In [26]:
spacy_doc = nlp(emma_ja)

In [30]:
pos_df = pd.DataFrame(columns=['token','pos_tag'])

In [34]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df,pd.DataFrame.from_records([{'token':token.text, 'pos_tag':token.pos_}])], ignore_index=True)

In [36]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [48]:
pos_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts', ascending=False)

In [50]:
pos_df_counts.head(10)

    token pos_tag  counts
88     of     ADP      14
49    had     AUX       9
54    her    PRON       9
6     and   CCONJ       8
112   the     DET       8
0       a     DET       6
115    to    PART       5
61     in     ADP       4
13   been     AUX       4
121  very     ADV       4

In [52]:
pos_df_poscounts = pos_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)

In [54]:
pos_df_poscounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
NUM       4
Name: token, dtype: int64

In [58]:
nouns = pos_df_counts[pos_df_counts.pos_tag == 'NOUN'][:10]
nouns

         token pos_tag  counts
46      friend    NOUN       3
48   governess    NOUN       3
82      mother    NOUN       2
35        emma    NOUN       2
28   daughters    NOUN       2
104    sisters    NOUN       2
131      years    NOUN       2
89      office    NOUN       1
78    mistress    NOUN       1
130      world    NOUN       1

In [60]:
import os
print(os.getcwd())

C:\Users\a